owner: BenjaminMichaelis
repo: SiteMonitor

assignees:
  - BenjaminMichaelis

sites:
  - name: Landing Page
    url: https://benjamin.michaelis.net/
  - name: Photography Site
    url: https://photography.michaelis.net/
  - name: Graph Sketchpad
    url: https://graphsketchpad.michaelis.net/
  - name: Village Meal Generator
    url: https://villagemealgenerator.michaelis.net/

status-website:
  cname: status.michaelis.net
  logoUrl: https://raw.githubusercontent.com/BenjaminMichaelis/SiteMonitor/main/assets/Icon.png
  name: Benjamin Michaelis Site Monitor
  introTitle: "This status page monitors sites for Benjamin Michaelis"
  introMessage: This is a status page which uses **real-time** data from my [GitHub repository](https://github.com/BenjaminMichaelis/SiteMonitor).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: More Links
      href: https://benjamin.michaelis.net/

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  graphsUpdate: ":bento: Update graphs [skip ci]"
  commitAuthorName: "BenjaminMichaelisBot"
  commitAuthorEmail: "bot@michaelis.net"

i18n:
  footer: This page is [open source]($REPO). Powered by [benjamin.michaelis.net](benjamin.michaelis.net)
